- name: Generate service manifest
  template:
    src: service.yml.j2
    dest: "/tmp/{{ item.name }}-svc.yaml"
  loop: "{{ services }}"

- name: Apply service with kubectl
  command: kubectl apply -f /tmp/{{ item.name }}-svc.yaml
  loop: "{{ services }}"

- name: Remove temporary service manifest
  file:
    path: "/tmp/{{ item.name }}-svc.yaml"
    state: absent
  loop: "{{ services }}"
