kind: IPAddressPool
metadata:
  name: lan-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.55.10.200-10.55.10.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: lan-announce
  namespace: metallb-system
spec:
  interfaces:
  - eth0