- hosts: masters[0]
  become: yes
  tasks:
    - name: Get latest Cilium CLI version
      uri:
        url: https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt
        return_content: yes
      register: cilium_cli_version

    - name: Set CLI_ARCH fact based on architecture
      set_fact:
        cli_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"

    - name: Download Cilium CLI tar.gz and sha256sum
      get_url:
        url: "https://github.com/cilium/cilium-cli/releases/download/{{ cilium_cli_version.content | trim }}/cilium-linux-{{ cli_arch }}.tar.gz{{ item }}"
        dest: "/tmp/cilium-linux-{{ cli_arch }}.tar.gz{{ item }}"
      loop:
        - ""
        - ".sha256sum"

    - name: Check sha256 checksum
      shell: "sha256sum --check /tmp/cilium-linux-{{ cli_arch }}.tar.gz.sha256sum"
      args:
        chdir: /tmp
      register: sha256_check
      failed_when: "'OK' not in sha256_check.stdout"

    - name: Extract and install Cilium CLI
      unarchive:
        src: "/tmp/cilium-linux-{{ cli_arch }}.tar.gz"
        dest: /usr/local/bin
        remote_src: yes

    - name: Remove downloaded tar and sha256sum
      file:
        path: "/tmp/cilium-linux-{{ cli_arch }}.tar.gz{{ item }}"
        state: absent
      loop:
        - ""
        - ".sha256sum"

    - name: Run cilium install
      command: cilium install
      environment:
        KUBECONFIG: /home/{{ default_user }}/.kube/config