- name: Configure Join Commands on Master Node
  hosts: masters[0]
  become: yes
  tasks:
    - name: Wait for node to be Ready
      shell: |
        if kubectl get node {{ groups['masters'][0] }} --no-headers | grep ' Ready'; then exit 0; else exit 1; fi
      register: node_status
      retries: 30
      delay: 10
      until: node_status.rc == 0
      environment:
        KUBECONFIG: /home/{{ default_user }}/.kube/config

    - name: Retrieve Join Command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Set Join Command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- name: Join Worker Nodes
  hosts: workers
  become: yes
  tasks:      
    - name: Join worker to cluster
      shell: "{{ hostvars[groups['masters'][0]].join_command }} >> node_joined.log"
      args:
        chdir: '/home/{{default_user}}'
        creates: node_joined.log

- name: Label worker nodes from master
  hosts: masters[0]
  become: yes
  tasks:
    - name: Label each worker node with node-role.kubernetes.io/worker
      shell: kubectl label node {{ item }} node-role.kubernetes.io/worker=""
      loop: "{{ groups['workers'] }}"
      environment:
        KUBECONFIG: /home/{{ default_user }}/.kube/config