- hosts: pvenodes[0]
  become: false
  gather_facts: false
  tasks:
    - name: Add master nodes to inventory
      add_host:
        name: "{{ item.name }}"
        ansible_host: "{{ item.ipv4_address.split('/')[0] }}"
        ansible_become_password: "{{ sudo_pass }}"
        ansible_ssh_private_key_file: "{{ ansible_key_file | replace('.pub', '') }}"
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
        groups:
          - masters
          - k8s_nodes
      loop: '{{ computers }}'
      when: item.role == "master"

    - name: Add worker nodes to inventory
      add_host:
        name: "{{ item.name }}"
        ansible_host: "{{ item.ipv4_address.split('/')[0] }}"
        ansible_become_password: "{{ sudo_pass }}"
        ansible_ssh_private_key_file: "{{ ansible_key_file | replace('.pub', '') }}"
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
        groups:
          - workers
          - k8s_nodes
      loop: '{{ computers }}'
      when: item.role == "worker"