- hosts: localhost
  become: false
  gather_facts: false      
  tasks:

  # Create variables files for images and VMs
  - name: Create Variables Files
    include_role:
      name: create_variables_file
    vars:
      variable_name: '{{item.name}}'
      group_name: '{{item.group}}'
    loop: 
      '{{variable_files}}'

- import_playbook: k8s_nodes.yml
- import_playbook: k8s_create_cluster.yml
- import_playbook: k8s_workers.yml
- import_playbook: k8s_masters.yml
- import_playbook: k8s_create_apps.yml