- name: Install metallb
  shell: |
    kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.14.9/config/manifests/metallb-native.yaml

- name: Wait for all MetalLB pods to be running
  shell: |
    kubectl wait --namespace metallb-system \
      --for=condition=Ready pods --all \
      --timeout=120s
  register: wait_result
  changed_when: false

- name: Create ConfigMap
  shell: |
    kubectl apply -f - <<EOF
    apiVersion: metallb.io/v1beta1
    kind: IPAddressPool
    metadata:
      name: lan-pool
      namespace: metallb-system
    spec:
      addresses:
      - 10.55.10.200-10.55.10.250
    ---
    apiVersion: metallb.io/v1beta1
    kind: L2Advertisement
    metadata:
      name: lan-announce
      namespace: metallb-system
    spec:
      interfaces:
      - eth0
    EOF