- name: Create an Empty file for Kubeadm configuring
  copy:
    content: ""
    dest: /etc/kubernetes/kubeadm-config.yaml
    force: no

- name: Configure container runtime
  blockinfile:
    path: /etc/kubernetes/kubeadm-config.yaml
    block: |
      kind: ClusterConfiguration
      apiVersion: kubeadm.k8s.io/v1beta3
      controlPlaneEndpoint: "10.55.10.101:6443"
      networking:
        podSubnet: "10.200.0.0/16"
        serviceSubnet: "10.96.0.0/12"
      ---
      kind: KubeletConfiguration
      apiVersion: kubelet.config.k8s.io/v1beta1
      runtimeRequestTimeout: "15m"
      cgroupDriver: "systemd"
      systemReserved:
        cpu: 100m
        memory: 350M
      kubeReserved:
        cpu: 100m
        memory: 50M
      enforceNodeAllocatable:
      - pods

- name: Initialize the cluster
  shell: kubeadm init --config /etc/kubernetes/kubeadm-config.yaml
  args:
    chdir: '/home/{{default_user}}'

- name: Create .kube directory
  become: true
  become_user: '{{default_user}}'
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: Copy admin.conf to User's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: '/home/{{default_user}}/.kube/config'
    remote_src: yes
    owner: '{{default_user}}'
