- hosts: masters[0]
  become: yes
  gather_facts: false
  environment:
    KUBECONFIG: /home/{{ default_user }}/.kube/config
  tasks:
  - name: Install Hubble
    shell: |
      cilium hubble enable --ui 

  - name: Create Hubble Service
    shell: |
      kubectl apply -f - <<EOF
      apiVersion: v1
      kind: Service
      metadata:
        name: hubble-ui
        namespace: kube-system
      spec:
        type: LoadBalancer
        selector:
          k8s-app: hubble-ui
        ports:
          - name: http
            port: 80
            targetPort: 8081
        loadBalancerIP: 10.55.10.201
      EOF