- hosts: masters[0]
  become: yes
  gather_facts: false
  environment:
    KUBECONFIG: /home/{{ default_user }}/.kube/config
  tasks:
    - name: Add metrics-server repo
      shell: |
        helm repo add metrics-server https://kubernetes-sigs.github.io/metrics-server/

    - name: Update Helm repo
      shell: |
        helm repo update

    - name: Install metrics-server helm chart
      shell: |
        helm install metrics-server metrics-server/metrics-server \
          --namespace kube-system \
          --set args[0]="--kubelet-insecure-tls"